create table tb_membro (data_nascimento date, idade integer, id bigserial not null, pg_id bigint, email varchar(255), nome varchar(255), sobrenome varchar(255), telefone varchar(255), primary key (id));
create table tb_pequeno_grupo (id bigserial not null, apelido varchar(255), lider varchar(255), nome varchar(255), primary key (id));
create table tb_user (role smallint check (role between 0 and 1), id bigserial not null, email varchar(255), nome varchar(255), password varchar(255), primary key (id));
create table tb_visitante (id bigserial not null, pg_id bigint, nome varchar(255), sexo varchar(255), sobrenome varchar(255), primary key (id));
alter table if exists tb_membro add constraint FK6hxuohe1r4nt73wfctbbc8vu foreign key (pg_id) references tb_pequeno_grupo;
alter table if exists tb_visitante add constraint FK8vip6xohwg6w9xr6wkwa306l4 foreign key (pg_id) references tb_pequeno_grupo;
INSERT INTO tb_pequeno_Grupo (nome, apelido, lider) VALUES ('Waldirene', 'Azul', 'Junior');
INSERT INTO tb_pequeno_Grupo (nome, apelido, lider) VALUES ('Pr. Alex', 'VERDE', 'Rhuan');
INSERT INTO tb_pequeno_Grupo (nome, apelido, lider) VALUES ('Amilton', 'AMARELO', 'Beto');
INSERT INTO tb_pequeno_Grupo (nome, apelido, lider) VALUES ('Yasmin', 'ROXO', 'Douglas');
INSERT INTO tb_user (nome, email, password, role) VALUES ('Eleilson','leo@gmail.com', '1234', 0);
INSERT INTO tb_user (nome, email, password, role) VALUES ('Junior','junior@gmail.com', '1234', 1);
INSERT INTO tb_user (nome, email, password, role) VALUES ('Rhuan','rhuan@gmail.com', '1234', 1);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (2, 'José Luiz', 'Ribeiro Junior', 'junior@gmail.com', '1988-10-07', 35, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (4, 'Marcus', 'Fereira Duarte', 'marcus@gmail.com', '1987-05-11', 37, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (2, 'Jaline', 'Pereira Fonseca', 'jaline@gmail.com', '1991-06-22', 30, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (1, 'Aline', 'Pereira Fonseca', 'aline@gmail.com', '1988-10-07', 40, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (1, 'Alex', 'Soares Fonseca', 'alex@gmail.com', '1967-01-14',65, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (3, 'Carlos','Henriques Silva', 'carlosx@gmail.com', '1970-09-14', 53, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (1, 'Gabriela', 'Lopez Marques', 'gabix@gmail.com', '1987-06-25', 41, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (2, 'João Arthur', 'Loureiro Ribeiro', 'joãox@gmail.com', '1981-04-19', 32, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (2, 'Ana Cristina', 'Loureiro da Silva ', 'anax@gmail.com', '1984-01-14', 28, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (1, 'Laura Ester', 'Soares Fonseca', 'laura@gmail.com', '1970-01-14',67, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (2, 'Ricardo', 'Chavier Galvão', 'ricardo@gmail.com', '1967-01-14', 70, 970312251);
INSERT INTO tb_visitante (nome, sobrenome, PG_id, sexo) VALUES ('Elias','Levia Silva', 3, 'Masculino');
INSERT INTO tb_visitante (nome, sobrenome, PG_id, sexo) VALUES ('Andre','Favale Nogueira', 1,'Masculino');
INSERT INTO tb_visitante (nome, sobrenome, PG_id, sexo) VALUES ('Maria','Laurindo Souza', 2, 'Feminino');
INSERT INTO tb_visitante (nome, sobrenome, PG_id, sexo) VALUES ('Emerson','Levia Silva', 2, 'Masculino');
INSERT INTO tb_visitante (nome, sobrenome, PG_id, sexo) VALUES ('José','Bueno Vera', 2, 'Masculino');
create table tb_membro (data_nascimento date, idade integer, id bigserial not null, pg_id bigint, email varchar(255), nome varchar(255), sobrenome varchar(255), telefone varchar(255), primary key (id));
create table tb_pequeno_grupo (id bigserial not null, apelido varchar(255), lider varchar(255), nome varchar(255), primary key (id));
create table tb_user (role smallint check (role between 0 and 1), id bigserial not null, email varchar(255), nome varchar(255), password varchar(255), primary key (id));
create table tb_visitante (id bigserial not null, pg_id bigint, nome varchar(255), sexo varchar(255), sobrenome varchar(255), primary key (id));
alter table if exists tb_membro add constraint FK6hxuohe1r4nt73wfctbbc8vu foreign key (pg_id) references tb_pequeno_grupo;
alter table if exists tb_visitante add constraint FK8vip6xohwg6w9xr6wkwa306l4 foreign key (pg_id) references tb_pequeno_grupo;
INSERT INTO tb_pequeno_Grupo (nome, apelido, lider) VALUES ('Waldirene', 'Azul', 'Junior');
INSERT INTO tb_pequeno_Grupo (nome, apelido, lider) VALUES ('Pr. Alex', 'VERDE', 'Rhuan');
INSERT INTO tb_pequeno_Grupo (nome, apelido, lider) VALUES ('Amilton', 'AMARELO', 'Beto');
INSERT INTO tb_pequeno_Grupo (nome, apelido, lider) VALUES ('Yasmin', 'ROXO', 'Douglas');
INSERT INTO tb_user (nome, email, password, role) VALUES ('Eleilson','leo@gmail.com', '1234', 0);
INSERT INTO tb_user (nome, email, password, role) VALUES ('Junior','junior@gmail.com', '1234', 1);
INSERT INTO tb_user (nome, email, password, role) VALUES ('Rhuan','rhuan@gmail.com', '1234', 1);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (2, 'José Luiz', 'Ribeiro Junior', 'junior@gmail.com', '1988-10-07', 35, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (4, 'Marcus', 'Fereira Duarte', 'marcus@gmail.com', '1987-05-11', 37, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (2, 'Jaline', 'Pereira Fonseca', 'jaline@gmail.com', '1991-06-22', 30, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (1, 'Aline', 'Pereira Fonseca', 'aline@gmail.com', '1988-10-07', 40, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (1, 'Alex', 'Soares Fonseca', 'alex@gmail.com', '1967-01-14',65, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (3, 'Carlos','Henriques Silva', 'carlosx@gmail.com', '1970-09-14', 53, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (1, 'Gabriela', 'Lopez Marques', 'gabix@gmail.com', '1987-06-25', 41, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (2, 'João Arthur', 'Loureiro Ribeiro', 'joãox@gmail.com', '1981-04-19', 32, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (2, 'Ana Cristina', 'Loureiro da Silva ', 'anax@gmail.com', '1984-01-14', 28, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (1, 'Laura Ester', 'Soares Fonseca', 'laura@gmail.com', '1970-01-14',67, 970312251);
INSERT INTO tb_membro (PG_id, nome, sobrenome, email, data_Nascimento, idade, telefone) VALUES (2, 'Ricardo', 'Chavier Galvão', 'ricardo@gmail.com', '1967-01-14', 70, 970312251);
INSERT INTO tb_visitante (nome, sobrenome, PG_id, sexo) VALUES ('Elias','Levia Silva', 3, 'Masculino');
INSERT INTO tb_visitante (nome, sobrenome, PG_id, sexo) VALUES ('Andre','Favale Nogueira', 1,'Masculino');
INSERT INTO tb_visitante (nome, sobrenome, PG_id, sexo) VALUES ('Maria','Laurindo Souza', 2, 'Feminino');
INSERT INTO tb_visitante (nome, sobrenome, PG_id, sexo) VALUES ('Emerson','Levia Silva', 2, 'Masculino');
INSERT INTO tb_visitante (nome, sobrenome, PG_id, sexo) VALUES ('José','Bueno Vera', 2, 'Masculino');
