export type visitante = {
  id: number;
  nome: string;
  sobrenome: string;
  email: string;
  idade: number;
  telefone: string;
  dataNascimento: Date;
  ebdCursoVisitante: [];
  opcaoCurso: string;
  apostila: boolean;
  visitanteStatus: string;
  cpf: string;
  estadoCivil: number;
  rua: string;
  cep: string;
  numero: number;
  bairro: string;
  cidade: string;
  complemento: string;
  url: string;
};
